// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © xsodus

//@version=4
strategy("Xsodus Super Trend Strategy Long Only V2", overlay=true)

startDate = input(title="Start Date", type=input.time, defval=timestamp("2018-01-01T00:00+07:00"))
endDate = input(title="End Date", type=input.time, defval=timestamp("9999-02-20T00:00+07:00"))


positionSize = input(title="Position Size", type=input.integer, defval=1)
mult = input(title="Super Trend Factor", type=input.float, defval=2)
len = input(title="Super Trend Length", type=input.integer, defval=12)

enableStopLoss = input(title="Enable stop loss", type=input.bool, defval=true)
stopLossPercentage =  input(title="Stop loss %", type=input.float, defval=20) * 0.01

var isOrdered = false

[superTrend, dir] = supertrend(mult, len)

buy = dir == -1 and dir == dir[0]
sell = dir == 1 and dir == dir[0]


// Calculate stop loss price condition.
longStopPrice  = strategy.position_avg_price * (1 - stopLossPercentage)

colResistance = dir == 1 and dir == dir[1] ? color.new(color.red, 0) : color.new(color.red, 100)
colSupport = dir == -1 and dir == dir[1] ? color.new(color.green, 0) : color.new(color.green, 100)

plot(superTrend, color = colResistance, linewidth=2)
plot(superTrend, color = colSupport, linewidth=2)

// Update open position status
if time > startDate and time < endDate and isOrdered == false and strategy.position_size == 0
    strategy.entry("Long",strategy.long,positionSize,when = buy)
    isOrdered := buy
    
// Update stop loss status
if strategy.position_size > 0 and enableStopLoss
    strategy.exit("Long",stop=longStopPrice)

// Update close position status
if strategy.position_size > 0
    strategy.close("Long", when = sell)
    
// Reset flag for opening a new order
if strategy.position_size == 0 and sell
    isOrdered := false